packages:
  - 'packages/*'
  - 'apps/*'

onlyBuiltDependencies:
  - esbuild
strictDepBuilds: false
minimumReleaseAgeExclude:
  - '@github/copilot-sdk@1.0.0'
allowBuilds:
  esbuild: set this to true or false
